--CREATE DATABASE EmployeeManagement;
USE EmployeeManagement;

CREATE TABLE TBL_DEPARTMENT(
	DEPARTMENT_ID INT PRIMARY KEY IDENTITY(1,1),
	SHORTNAME VARCHAR(5),
	NAME NVARCHAR(50)
);


CREATE TABLE TBL_EMPLOYEE(
	EMPLOYEE_ID INT PRIMARY KEY IDENTITY(1,1),
	FIRST_NAME NVARCHAR(20) NOT NULL, 
	LASTNAME NVARCHAR(20) UNIQUE,
	SALARY DECIMAL(9,2) NOT NULL,
	DEPARTMENT_FID INT REFERENCES TBL_DEPARTMENT,
	PERMANENT CHAR(1) NOT NULL,
	CONSTRAINT permanentCheck CHECK(PERMANENT = 'Y' OR PERMANENT = 'N')
);

SELECT * FROM TBL_DEPARTMENT;
SELECT * FROM TBL_EMPLOYEE;

--INSERT INTO TBL_DEPARTMENT VALUES ('eng', 'Engineering');
--INSERT INTO TBL_DEPARTMENT VALUES ('mkt', 'Marketting');
--INSERT INTO TBL_DEPARTMENT VALUES ('fin', 'Finance');
--INSERT INTO TBL_DEPARTMENT VALUES ('bus', 'Business');

--INSERT INTO TBL_EMPLOYEE VALUES ('John', 'Write', 5000.00, 1, 'Y' );
--INSERT INTO TBL_EMPLOYEE VALUES ('Andrew', 'White', 4000.00, 2, 'Y' );
--INSERT INTO TBL_EMPLOYEE VALUES ('Nick', 'Compton', 5000.00, 3, 'Y' );
--INSERT INTO TBL_EMPLOYEE VALUES ('Mitch', 'Starc', 5000.00, 4, 'N' );
--INSERT INTO TBL_EMPLOYEE VALUES ('James', 'Anderson', 3000.00, 1, 'N' );