//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dataAccess_EF.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_EMPLOYEE
    {
        public int EMPLOYEE_ID { get; set; }
        public string FIRST_NAME { get; set; }
        public string LASTNAME { get; set; }
        public decimal SALARY { get; set; }
        public Nullable<int> DEPARTMENT_FID { get; set; }
        public string PERMANENT { get; set; }
    
        public virtual TBL_DEPARTMENT TBL_DEPARTMENT { get; set; }
    }
}
