//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dataAccess_EF.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DEPARTMENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_DEPARTMENT()
        {
            this.TBL_EMPLOYEE = new HashSet<TBL_EMPLOYEE>();
        }
    
        public int DEPARTMENT_ID { get; set; }
        public string SHORTNAME { get; set; }
        public string NAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_EMPLOYEE> TBL_EMPLOYEE { get; set; }
    }
}
